using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Micromouse_Algo_Sim_C_sharp
{
    /// <summary>
    /// All mapping and fastest path algorithms
    /// </summary>
    [Author("Joseph Fortino and Nathan Diehl (generated by cmd", 1.0)]
    public static class Algorithms
    {
        public delegate bool MappingAlgorithm(Maze m, Robot r);
        public delegate bool FastestPathAlgorithm(List<Direction> path, Maze m);

    }
}
