using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Micromouse_Algo_Sim_C_sharp
{
    /// <summary>
    /// Represents a position in 2 dimensional space.
    /// </summary>
    [Author("Joseph Fortino and Nathan Diehl (generated by cmd", 1.0)]
    public struct Position
    {
        public int X;
        public int Y;

        public Position() {
            X = -1;
            Y = -1;
        }

        public Position(int x, int y) {
            X = x;
            Y = y;
        }
    }
}
