using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Micromouse_Algo_Sim_C_sharp
{
    /// <summary>
    /// A virtual representation of the robot.
    /// </summary>
    [Author("Joseph Fortino and Nathan Diehl (generated by cmd", 1.0)]
    public class Robot
    {
        private Position position;

        public List<Direction> Scan()
        {
            //TODO: write code.
            throw new NotImplementedException("Write the code first.");
        }

        public Position GetPosition()
        {
            return position;
        }

        public void Move(Direction direction)
        {
            //TODO: write code.
            throw new NotImplementedException("Write the code first.");
        }
    }
}
